### ISSUE TITLE
レビューがスムーズに行えない

### ISSUE THREAD

**Issue by sohey-dr** [mokupuro/circle-web#26]
## 背景

レビューがスムーズに行えない

## 目的

レビューの流れを理解しやすくなり、それと同時にPRをスムーズに行えるようになる

## タスク

- [ ] 開発の流れの粒度をあげる
- [ ] PR本文のテンプレートの作成

## その他メモ

現在のissueのテンプレートがバックエンド専用臭いから変えたみあり

**Comment by sohey-dr** [comment]
@tamaki8021 
対応しても大丈夫？
何か問題あったら言って欲しい！

**Comment by tamaki8021** [comment]
@sohey-dr 
好きに変えても問題ないです！
